Solution_OOP_Single_Inheritance
mate-academy/py-herbivores-and-carnivores pull request #1030
Opened 2024-03-27 09:20 UTC by IraMladanovych02

2024-03-27 10:20 UTC, Dimosphen1 requested changes
Several changes were requested. Make sure that all checks pass

2024-03-27 10:20 UTC, Dimosphen1 commented on tests/__init__.py
There is no need to delete this file, remove deletion from the PR, please

2024-03-27 10:20 UTC, Dimosphen1 commented on tests/test_main.py
There is no need to delete this file, remove deletion from the PR, please

2024-03-27 10:20 UTC, Dimosphen1 commented on app/main.py
> +print(Animal.alive)
Remove these lines, there is no need to have them here

2024-03-27 10:20 UTC, Dimosphen1 commented on app/main.py
> +    def bite(animal):
Add type annotation to all methods

2024-03-27 10:20 UTC, Dimosphen1 commented on app/main.py
> +        self.hidden = not self.hidden
Add blank lines between different classes

2024-03-27 10:20 UTC, Dimosphen1 commented on app/main.py
> +        super().__init__(name=name)
There is no need to duplicate `__init__` in this class and in the `Carnivore` class as well, remove them and rely on the parent class implementation

2024-03-28 13:15 UTC, pavlopro requested changes
Tests Failed

2024-06-10 19:08 UTC, closed without merging