Solution
mate-academy/py-herbivores-and-carnivores pull request #1399
Opened 2024-12-07 10:32 UTC by taraskhom

2024-12-07 16:11 UTC, DanilTrukhanov approved these changes
Good job!

2024-12-07 16:11 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-07 17:20 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-07 18:40 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-07 20:00 UTC, mateacademy-ai-mentor reviewed
Sorry, the pull request review was unsuccessful for the following reasons:

> [!WARNING]
> **There are no files to review.** Please make sure that you have added files to the pull request. Some files and directories may be ignored from the review or failed to load.
> <sub>*[CODE: 4]*</sub>

**Additional info:**
*Ignored files list:*
- `app/main.py`

If the issue is within your control, please address it.
The next review attempt <ins>will automatically launch</ins> in 1 hour.
If you believe this is an error or need assistance, please contact the support team.

2024-12-09 17:59 UTC, L1nk3rrr requested changes
Almost done! Some point for your improvements at comments

2024-12-09 17:59 UTC, L1nk3rrr commented on app/main.py
> +        if self.health > 0:
Task don't require that `if`

2024-12-09 17:59 UTC, L1nk3rrr commented on app/main.py
> +    def bite(animal: Herbivore | Carnivore) -> None:
Carnivore is not waited here, only Herbivore

2024-12-10 12:56 UTC, petrykivd approved these changes
Nice ! 👍

2024-12-10 12:56 UTC, petrykivd commented on app/main.py
> +                Animal.alive.remove(animal)
This check may not be nested

2026-04-08 10:18 UTC, closed without merging