Solution
mate-academy/py-herbivores-and-carnivores pull request #143
Opened 2022-09-17 11:43 UTC by AVyha

2022-09-19 09:02 UTC, wQuelS requested changes

2022-09-19 09:02 UTC, wQuelS commented on app/main.py
> +            Animal.alive.pop(Animal.alive.index(victim))
consider using remove instead of pop. index() is not so reliable

2022-09-19 09:02 UTC, wQuelS commented on app/main.py
> +    def bite(victim):
add type annotation to function and arg

2022-09-19 09:36 UTC, wQuelS approved these changes
looks good imo

2022-09-23 08:25 UTC, Y-Havryliv requested changes

2022-09-23 08:25 UTC, Y-Havryliv commented on app/main.py
> +    def __init__(self, name, health: int = 100):
add type annotations

2022-09-23 08:25 UTC, Y-Havryliv commented on app/main.py
> +        return f"{{" \
rewrite it, use `( )` for multiline strings

2022-09-23 08:57 UTC, Y-Havryliv requested changes

2022-09-23 08:57 UTC, Y-Havryliv commented on app/main.py
> +            victim.alive.remove(victim)
it's better to get access to class attributes using class name(`Animal`)

2022-09-23 09:14 UTC, Y-Havryliv approved these changes
Nice!

2024-12-01 14:32 UTC, closed without merging