Solution
mate-academy/py-herbivores-and-carnivores pull request #353
Opened 2023-02-10 12:17 UTC by viktoria-rybenchuk

2023-02-10 12:58 UTC, NazarHladaniuk approved these changes

2023-02-10 13:35 UTC, Serhii-Leonenko requested changes

2023-02-10 13:35 UTC, Serhii-Leonenko commented on app/main.py
> +    ) -> None:
Fix indentation here, move name to the new line to increase readability

2023-02-10 13:35 UTC, Serhii-Leonenko commented on app/main.py
> +            Animal.alive.remove(herbivore)
The method should be static, self is redudant

2023-02-10 13:35 UTC, Serhii-Leonenko commented on app/main.py
> +        return f"{{Name: {name}, Health: {health}, Hidden: {hidden}}}"
these variables are redundant in this case. Use brackets to wrap f-string

2023-02-13 12:36 UTC, YuriiKindrat requested changes

2023-02-13 12:36 UTC, YuriiKindrat commented on app/main.py
> +               f" Hidden: {self.hidden}}}"
try not to use " \ " here, use brackets to break the line

2023-02-13 13:30 UTC, YuriiKindrat approved these changes

2024-10-25 12:19 UTC, merged