implement 3 classes Carnivore/Herbivore/Animal
mate-academy/py-herbivores-and-carnivores pull request #945
Opened 2024-02-21 18:13 UTC by MaxSEngineer

2024-02-21 18:59 UTC, vsmutok requested changes

2024-02-21 18:59 UTC, vsmutok commented on app/main.py
> +                super().alive.remove(animal)
```suggestion
    @staticmethod
    def bite(other_animal: Herbivore) -> None:
        if isinstance(other_animal, Herbivore) and not other_animal.hidden:
            other_animal.health -= 50
            other_animal.check_if_alive()
```

2024-02-21 18:59 UTC, vsmutok commented on app/main.py
> +        self.hidden = True if not self.hidden else False
```suggestion
        self.hidden = not self.hidden
```

2024-02-22 19:56 UTC, MaxSEngineer commented on app/main.py
> +                super().alive.remove(animal)
Thanks, its really more clear code, i don't know why i used loop)

2024-02-22 19:57 UTC, MaxSEngineer commented on app/main.py
> +        self.hidden = True if not self.hidden else False
Makes sense so in short thanks

2024-04-28 08:51 UTC, closed without merging